-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 11:50:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project-ss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project-ss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project-ss` DEFAULT CHARACTER SET utf8 ;
USE `project-ss` ;

-- -----------------------------------------------------
-- Table `project-ss`.`locatie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`locatie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stad` VARCHAR(255) NOT NULL,
  `adres` VARCHAR(255) NOT NULL,
  `postcode` VARCHAR(6) NOT NULL,
  `longitude` VARCHAR(255) NULL,
  `latitude` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`functie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`functie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `extra info` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`gebruikers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`gebruikers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `achternaam` VARCHAR(254) NOT NULL,
  `initialen` VARCHAR(10) NOT NULL,
  `Geslacht` TINYINT NOT NULL,
  `locatie-id` INT NOT NULL,
  `functie-id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `gebruikers_loactie_idx` (`locatie-id` ASC),
  INDEX `gebruikers_functie_idx` (`functie-id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `gebruikers_loactie`
    FOREIGN KEY (`locatie-id`)
    REFERENCES `project-ss`.`locatie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gebruikers_functie`
    FOREIGN KEY (`functie-id`)
    REFERENCES `project-ss`.`functie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`id_gegevens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`id_gegevens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gebruikers_id` INT NULL,
  `bsn` VARCHAR(15) NULL,
  `vervaldatum` DATE NULL,
  `patient_nummer` VARCHAR(45) NULL,
  `zorg_id` INT NULL,
  `Zorgvezekeraar` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_gegevens_gebruikers_idx` (`gebruikers_id` ASC),
  CONSTRAINT `id_gegevens_gebruikers`
    FOREIGN KEY (`gebruikers_id`)
    REFERENCES `project-ss`.`gebruikers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`raporteren`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`raporteren` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Protocol` TEXT NULL,
  `gebruikers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `gebruikers_id_UNIQUE` (`gebruikers_id` ASC),
  CONSTRAINT `raporteren_gebruikers`
    FOREIGN KEY (`gebruikers_id`)
    REFERENCES `project-ss`.`gebruikers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`opmerekingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`opmerekingen` (
  `id` INT NOT NULL,
  `opmereking` TEXT NOT NULL,
  `raport_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `opmerkingen_raproteren_idx` (`raport_id` ASC),
  CONSTRAINT `opmerkingen_raproteren`
    FOREIGN KEY (`raport_id`)
    REFERENCES `project-ss`.`raporteren` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`Rooster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`Rooster` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gebruikers-id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `rooster_gebruikers_idx` (`gebruikers-id` ASC),
  CONSTRAINT `rooster_gebruikers`
    FOREIGN KEY (`gebruikers-id`)
    REFERENCES `project-ss`.`gebruikers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`rooster_gebruikers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`rooster_gebruikers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rooster-id` INT NOT NULL,
  `gebruikers-id` INT NULL,
  `wanneer` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `rooster_gebruikers_rooster_idx` (`rooster-id` ASC),
  INDEX `rooster_gebruikers_gebruikers_idx` (`gebruikers-id` ASC),
  CONSTRAINT `rooster_gebruikers_rooster`
    FOREIGN KEY (`rooster-id`)
    REFERENCES `project-ss`.`Rooster` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rooster_gebruikers_gebruikers`
    FOREIGN KEY (`gebruikers-id`)
    REFERENCES `project-ss`.`gebruikers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
