-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 10:49:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project-ss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project-ss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project-ss` DEFAULT CHARACTER SET utf8 ;
USE `project-ss` ;

-- -----------------------------------------------------
-- Table `project-ss`.`locatie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`locatie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stad` VARCHAR(255) NOT NULL,
  `adres` VARCHAR(255) NOT NULL,
  `postcode` VARCHAR(6) NOT NULL,
  `longitude` VARCHAR(255) NULL,
  `latitude` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`functie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`functie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `extra info` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`gebruikers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`gebruikers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  `achternaam` VARCHAR(254) NOT NULL,
  `initialen` VARCHAR(10) NOT NULL,
  `Geslacht` TINYINT NOT NULL,
  `locatie_id` INT NOT NULL,
  `functie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`id_gegevens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`id_gegevens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gebruikers_id` INT NULL,
  `bsn` VARCHAR(15) NULL,
  `vervaldatum` DATE NULL,
  `patient_nummer` VARCHAR(45) NULL,
  `zorg_id` INT NULL,
  `Zorgvezekeraar` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`raporteren`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`raporteren` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Protocol` TEXT NULL,
  `gebruikers_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `gebruikers_id_UNIQUE` (`gebruikers_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`opmerkingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`opmerkingen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titel` VARCHAR(255) NOT NULL,
  `opmerking` TEXT NOT NULL,
  `raport_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`rooster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`rooster` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gebruikers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project-ss`.`client_in_rooster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project-ss`.`client_in_rooster` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rooster_id` INT NOT NULL,
  `gebruikers_id` INT NOT NULL,
  `dag_van_de_week` TINYINT NOT NULL,
  `tijd` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
